### PR TITLE
Crystal 1.0.0

### PR DESCRIPTION
**Pull request by kalinon**
Recent update and cleanup to get this working again for Crystal 1.0.0

This also depends on https://github.com/Papierkorb/bindgen/pull/115 which the shards.yml is pulling from my fork.

### CODE REVIEW

**Comment by docelic** [comment]
Looks good to me at a glance, let's see in a day or two if Stefan has any additional comments.

Now that bindgen patch has been accepted, can we get shard.yml back to bindgen's repo instead of your fork?

Thanks!

**Comment by kalinon** [comment]
> Looks good to me at a glance, let's see in a day or two if Stefan has any additional comments.
> 
> Now that bindgen patch has been accepted, can we get shard.yml back to bindgen's repo instead of your fork?
> 
> Thanks!

Yep, that sounds good. That was kinda the plan. ill update this once bindgen is merged.

**Comment by kalinon** [comment]
@Papierkorb this is back on the official shard

**Comment by Papierkorb** [comment]
I see you added a Dockerfile.  What's its exact purpose, and how does one use it?

**Comment by kalinon** [comment]
I can remove it as its not complete. The idea was to be able to test binding generation for linux or different QT versions via a docker image. I was using it to test linux vs darwin builds of QT.

**Comment by Papierkorb** [comment]
That's a really good thing to have once it's ready.  But removing it for now is better.

**Comment by kalinon** [comment]
missed a few fixes needed for this in bindgen. so https://github.com/Papierkorb/bindgen/pull/116 is needed.

**Comment by kalinon** [comment]
@Papierkorb i just updated some of the new type/enum definitions i added for the UI parser branch. And reverted the default build `support/generate_bindings.cr` back to linux. Other than that i haven't had to make any changes in awhile, so this is probably good to go. 

I did chomp some prefixes off enums and the adding of new classes may warrent a minor version release update on next release.

**Comment by docelic** [comment]
Hey @kalinon, re. the new enums/classes, I recall that we were unable to add new ones just like that, because they prevented the bindings build working on earlier versions of Qt which do not have them defined. I believe this is why the comparison `newer_or(...ver...)` was added some time ago (so that one could use it for conditional definition), but then these conditional defines were not actually used yet.

**Comment by acoolstraw** [comment]
bump, please fix conflicting files

**Comment by kalinon** [comment]
@acoolstraw done

**Pull request merged**
