### PR TITLE
add missing QCursor

### PR DESCRIPTION
**Pull request by foliea**

### CODE REVIEW

**Comment by Papierkorb** [comment]
Can you also add related enums, like `Qt::CursorShape`?

**Comment by foliea** [comment]
@Papierkorb I added `Qt::CursorShape`, also added related `Qt::Bitmap`.

**Comment by Papierkorb** [comment]
You can add `QBitmap` too.  QBitmap inherits QPixmap, so `QBitmap: Bitmap` must come after the Pixmap line to preserve this order in the resulting Crystal code.  Otherwise, Crystal complains that it doesn't know `Pixmap` yet, which is defined just after the `Bitmap` class.

In your case, all you need to do is to swap the lines of Pixmap and Bitmap in the `classes.conf`.

**Comment by Papierkorb** [comment]
The line I use to regenerate  is: `BINDING_PLATFORM='linux-gnu-x86_64-qt5.10' lib/bindgen/tool.sh qt.yml --stats && crystal spec`.  If that passes, it's good.  (You may have to change the BINDING_PLATFORM though)

**Comment by foliea** [comment]
I swapped it.

Here is the result of the above command:

```
Stage                           Heap     Duration
  Find paths                      0 B      00:00:00.124993000 0%
  Parse C++                       +28 MiB  00:00:05.036435000 24%
  Build graph                     0 B      00:00:00.012928000 0%
  Processors                      +24 MiB  00:00:00.740680000 3%
    inheritance                   0 B      00:00:00.002931000 0%
    default_constructor           0 B      00:00:00.000102000 0%
    copy_structs                  0 B      00:00:00.000049000 0%
    macros                        0 B      00:00:00.000038000 0%
    functions                     0 B      00:00:00.000009000 0%
    filter_methods                0 B      00:00:00.022287000 3%
    auto_container_instantiation  0 B      00:00:00.011688000 1%
    instantiate_containers        0 B      00:00:00.000621000 0%
    enums                         0 B      00:00:00.005333000 0%
    qt                            0 B      00:00:00.008222000 1%
    crystal_wrapper               0 B      00:00:00.139988000 18%
    virtual_override              0 B      00:00:00.057115000 7%
    cpp_wrapper                   +8 MiB   00:00:00.110103000 14%
    crystal_binding               +8 MiB   00:00:00.098267000 13%
    sanity_check                  +8 MiB   00:00:00.283631000 38%
  Generators                      +8 MiB   00:00:14.479445000 70%
    cpp                           +8 MiB   00:00:00.124418000 0%
    cpp build                     0 B      00:00:13.994518000 96%
    crystal                       0 B      00:00:00.360401000 2%
    crystal build                 0 B      00:00:00.000002000 0%
  Total time: 00:00:20.394481000
  Heap size : 61 MiB
...............................Qt 5.10.0, linked to 5.10.0 / Crystal 0.24.1
.

Finished in 505 microseconds
32 examples, 0 failures, 0 errors, 0 pending
```

**Comment by Papierkorb** [comment]
Have you committed and pushed after the swap?

**Comment by foliea** [comment]
I guess I forgot :), it's done now

**Comment by Papierkorb** [comment]
Thanks!

**Pull request merged**
