### PR TITLE
Qt patch number

### PR DESCRIPTION
**Pull request by f-fr**

### CODE REVIEW

**Comment by docelic** [comment]
Heya, thanks for the patch!

Btw, I believe this was simply left at revision .0 always because the minor revision does not change the API, so any revision is good for generating the bindings. But if Qt decides to delete .0 but keep a later revision in the archive, then that's a problem so your patch is useful.

Also the idea of just trying multiple URLs (archive/new_archive) is a nice one! Previously we were trying to identify exactly where the file is which was more complicated.

**Comment by f-fr** [comment]
Actually I needed 5.11.3 because 5.11.0 does not compile due to some bad include-file somewhere in Qt. This seems to be fixed in 5.11.3.

I know this is a little OT but: Unfortunately, 5.11.3 doesn't compile either, because `QAbstractItemModel` is not defined. The reason is probably that the "itemmodel" configuration option of Qt has not been set. Any idea how I could fix this?

**Comment by docelic** [comment]
> Actually I needed 5.11.3 because 5.11.0 does not compile due to some bad include-file somewhere in Qt. This seems to be fixed in 5.11.3.

Ah yes! I remember seeing it as well.

**Comment by docelic** [comment]
For 5.13 issue, try seeing one of @ZaWertun's commits in https://github.com/ZaWertun/qt5.cr/commits/master 

He got it working. The only reason why those changes weren't integrated is because we needed conditional `if` directives in .yml so that new enums etc. would not be causing compilation errors on earlier versions.
The commit where the necessary directives for conditional inclusion were added to bindgen is https://github.com/Papierkorb/bindgen/pull/56 so theoretically there are no blockers to do it now (the directives are `newer_or` and `older_or`).

**Pull request merged**
